Konosuba TXPL support
DCNick3/ShinDataUtil pull request #7
Opened 2022-07-09 12:17 UTC by nikvoid

LZLR Compression (currently simple and uneffective compression only), TexPool (.txl and .tlz) extracting and building, Tex encoding

2022-07-09 13:38 UTC, DCNick3 requested changes
Overall - seems good, thanks for taking time to upstream =)

2022-07-09 13:38 UTC, DCNick3 commented on Program.cs
> +                Console.Error.WriteLine($"           {(uint)fmt}  {fmt}");
nit: add tab

2022-07-09 13:38 UTC, DCNick3 commented on Program.cs
> +                Int32.TryParse(args[args.IndexOf("--format") + 1], out var fmt);
I think using `Enum.TryParse` to parse symbolic names for the formats would be better for the user. ~~Also please check whether the parse was successful and raise an error if it was not =)~~ Scratch that, the enum is checked against the list from `GetAvailableFormats`, that's fine

2022-07-09 13:48 UTC, nikvoid commented on Program.cs
> +                Console.Error.WriteLine($"           {(uint)fmt}  {fmt}");
I decided to leave it without tab intentionally, just to make it look like in console output
P.S. можем на русском)

2022-07-09 13:51 UTC, DCNick3 commented on Program.cs
> +                Console.Error.WriteLine($"           {(uint)fmt}  {fmt}");
Справедливо

2022-07-09 13:57 UTC, nikvoid commented on Program.cs
> +                Console.Error.WriteLine($"           {(uint)fmt}  {fmt}");
Возможно...

2022-07-09 13:58 UTC, nikvoid commented on Program.cs
> +                Int32.TryParse(args[args.IndexOf("--format") + 1], out var fmt);
Сделаю тогда ввод имени формата вместо номера

2022-07-11 07:18 UTC, DCNick3 commented
Норм

2022-07-11 07:18 UTC, merged